const D=window.BARADE_DATA,$=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(n)||0),pct=n=>(Number.isFinite(Number(n))?Number(n):0).toFixed(1)+'%',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COLORS=['#31ecff','#a855f7','#ff4fd8','#35efad','#ffcc65','#5f8cff','#00c3ff','#ff6b81'];
const sel={item:new Set(),line:new Set(),state:new Set(),zone:new Set(),month:new Set()};
const defs={item:{idx:1,v:D.i,l:'All Items'},line:{idx:2,v:D.l,l:'All Lines'},state:{idx:3,v:D.s,l:'All States'},zone:{idx:4,v:D.z,l:'All Zones'},month:{idx:0,v:D.mo,l:'All Months'}};
const multi={};
function rowMatch(r,skip=null){return Object.entries(defs).every(([k,d])=>k===skip||!sel[k].size||sel[k].has(d.v[r[d.idx]]))}
function available(k){const d=defs[k],out=new Set();for(const r of D.r)if(rowMatch(r,k))out.add(d.v[r[d.idx]]);return out}
function mk(k){const s=$(k);s.style.display='none';const w=document.createElement('div');w.className='multi';s.after(w);function draw(){const ok=available(k);[...sel[k]].forEach(v=>!ok.has(v)&&sel[k].delete(v));const label=!sel[k].size?defs[k].l:sel[k].size===1?[...sel[k]][0]:`${sel[k].size} selected`;w.innerHTML=`<button class="multiBtn" type="button"><span>${esc(label)}</span><b>⌄</b></button><div class="multiMenu"><div class="multiActions"><button data-a="all">Select All</button><button data-a="close">Close</button></div><div class="multiList">${defs[k].v.filter(v=>ok.has(v)).map(v=>`<label><input type="checkbox" value="${esc(v)}" ${sel[k].has(v)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div></div>`;w.querySelector('.multiBtn').onclick=e=>{e.stopPropagation();document.querySelectorAll('.multi.open').forEach(x=>x!==w&&x.classList.remove('open'));w.classList.toggle('open')};w.querySelector('.multiMenu').onclick=e=>e.stopPropagation();w.querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?sel[k].add(x.value):sel[k].delete(x.value);refresh();render()});w.querySelector('[data-a=all]').onclick=()=>{sel[k].clear();refresh();render()};w.querySelector('[data-a=close]').onclick=()=>w.classList.remove('open')}multi[k]={draw};draw()}
function refresh(){Object.values(multi).forEach(x=>x.draw())}Object.keys(defs).forEach(mk);document.addEventListener('click',()=>document.querySelectorAll('.multi.open').forEach(x=>x.classList.remove('open')));
const money=(r,i)=>(Number(r[i])||0)/100;
function rows(){return D.r.filter(r=>rowMatch(r))}
function sums(a){let t=Array(7).fill(0);a.forEach(r=>{for(let j=0;j<7;j++)t[j]+=money(r,5+j)});return t}
function enrich(name,t,extras={}){return{name,...extras,s25:t[0],s26:t[1],sold26:t[2],ret26:t[3],exp26:t[4],qty26:t[5],bonus26:t[6],growth:t[0]>0?100*(t[1]-t[0])/t[0]:null,expiryRate:t[2]?100*t[4]/t[2]:0,returnRate:t[2]?100*t[3]/t[2]:0,bonusRate:t[5]?100*t[6]/t[5]:0}}
function group(a,idx,names){const m=new Map();for(const r of a){let o=m.get(r[idx]);if(!o){o={t:Array(7).fill(0),states:new Set(),lines:new Set()};m.set(r[idx],o)}for(let j=0;j<7;j++)o.t[j]+=money(r,5+j);o.states.add(D.s[r[3]]);o.lines.add(D.l[r[2]])}return[...m].map(([k,o])=>enrich(names[k],o.t,{states:o.states,lines:o.lines}))}
function bars(id,a,key,opt={}){const e=$(id);a=[...a].filter(x=>x[key]!=null).sort((x,y)=>(opt.asc?1:-1)*((x[key]||0)-(y[key]||0))).slice(0,opt.n||14);const mx=Math.max(1,...a.map(x=>Math.abs(x[key]||0)));e.innerHTML=a.length?a.map(x=>`<div class="bar"><div class="name" title="${esc(x.name)}">${esc(x.name)}</div><div class="track"><div class="fill" style="width:${Math.abs(x[key]||0)/mx*100}%;${opt.color?`background:${opt.color}`:''}"></div></div><div class="value ${opt.cls?opt.cls(x):''}">${opt.percent?pct(x[key]):fmt(x[key])}</div></div>`).join(''):'<div class="note">No matching data</div>'}
function compare(a){a=[...a].sort((x,y)=>y.s26-x.s26).slice(0,14);const mx=Math.max(1,...a.flatMap(x=>[x.s25,x.s26]));$('zoneCompare').innerHTML=a.map(x=>`<div class="bar"><div class="name">${esc(x.name)}</div><div><div class="track"><div class="fill" style="width:${Math.max(0,x.s26)/mx*100}%;background:#31ecff"></div></div><div class="track" style="margin-top:3px"><div class="fill" style="width:${Math.max(0,x.s25)/mx*100}%;background:#a855f7"></div></div></div><div class="value">${fmt(x.s26)}</div></div>`).join('')}
function donut(a,total){a=[...a].filter(x=>x.s26>0).sort((x,y)=>y.s26-x.s26);let p=a.slice(0,7),known=p.reduce((s,x)=>s+x.s26,0);if(total-known>1)p.push({name:'Others',s26:total-known});let acc=0,st=[];p.forEach((x,i)=>{const v=total?x.s26/total*100:0;st.push(`${COLORS[i%COLORS.length]} ${acc}% ${acc+v}%`);acc+=v});$('donut').style.background=p.length?`conic-gradient(${st.join(',')})`:'rgba(255,255,255,.05)';$('donutTotal').textContent=fmt(total);$('donutLegend').innerHTML=p.map((x,i)=>`<div class="legendItem"><span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${COLORS[i%COLORS.length]};margin-inline-end:6px"></i>${esc(x.name)}</span><strong>${pct(total?100*x.s26/total:0)}</strong></div>`).join('')}
function trend(a){const chosen=D.mo.map((m,i)=>({m,i})).filter(x=>!sel.month.size||sel.month.has(x.m));const vals=[0,1].map(y=>chosen.map(({i})=>a.filter(r=>r[0]===i).reduce((s,r)=>s+money(r,5+y),0)));const mx=Math.max(1,...vals[0],...vals[1]),n=Math.max(1,chosen.length),step=n>1?800/(n-1):0,xy=(v,i)=>[55+i*step,270-v/mx*220],path=v=>v.map((x,i)=>(i?'L':'M')+xy(x,i).join(',')).join(' ');let grid='';for(let i=0;i<5;i++){const y=30+i*55;grid+=`<line x1="45" y1="${y}" x2="865" y2="${y}" class="gridline"/>`}$('trend').innerHTML=grid+`<path d="${path(vals[0])}" fill="none" stroke="#a855f7" stroke-width="4"/><path d="${path(vals[1])}" fill="none" stroke="#31ecff" stroke-width="4"/>`+chosen.map((x,i)=>`<text x="${55+i*step}" y="300" class="axis" text-anchor="middle">${x.m.slice(0,3)}</text>`).join('')}
function cust(){const q=($('search').value||'').trim().toLowerCase(),m=new Map();for(const r of D.c){const mon=D.mo[r[2]],state=D.s[r[3]],zone=D.z[r[4]];if(sel.month.size&&!sel.month.has(mon))continue;if(sel.state.size&&!sel.state.has(state))continue;if(sel.zone.size&&!sel.zone.has(zone))continue;const acct=D.n[r[0]],name=D.n[r[1]];if(q&&!name.toLowerCase().includes(q)&&!acct.toLowerCase().includes(q))continue;const k=r[0]+'|'+r[1],o=m.get(k)||{acct,name,s25:0,s26:0,states:new Set(),zones:new Set()};o.s25+=r[5]/100;o.s26+=r[6]/100;o.states.add(state);o.zones.add(zone);m.set(k,o)}const all=[...m.values()].filter(x=>x.s25>0).map(x=>({...x,growth:100*(x.s26-x.s25)/x.s25,delta:x.s26-x.s25}));return{g:all.filter(x=>x.growth>=10).sort((a,b)=>b.delta-a.delta).slice(0,10),d:all.filter(x=>x.growth<=-10).sort((a,b)=>a.delta-b.delta).slice(0,10),gc:all.filter(x=>x.growth>=10).length,dc:all.filter(x=>x.growth<=-10).length}}
function ctable(id,a){$(id).innerHTML=a.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.acct)}</td><td>${esc([...x.states].join(', '))}</td><td>${esc([...x.zones].join(', '))}</td><td>${fmt(x.s25)}</td><td>${fmt(x.s26)}</td><td class="${x.growth>=0?'pos':'neg'}">${pct(x.growth)}</td><td class="${x.delta>=0?'pos':'neg'}">${x.delta>=0?'+':''}${fmt(x.delta)}</td></tr>`).join('')||'<tr><td colspan="9">No matching customers</td></tr>'}
function render(){const a=rows(),t=sums(a),z=group(a,4,D.z),p=group(a,1,D.i),g=t[0]?100*(t[1]-t[0])/t[0]:null,top=[...z].sort((a,b)=>b.s26-a.s26)[0],c=cust();$('sales26').textContent=fmt(t[1]);$('sales25').textContent='2025: '+fmt(t[0]);$('growth').textContent=g==null?'—':pct(g);$('growth').className=g==null?'':g>=0?'pos':'neg';$('expiry').textContent=fmt(t[4]);$('expiryRate').textContent=pct(t[2]?100*t[4]/t[2]:0)+' of Sold Amount';$('returnRate').textContent=pct(t[2]?100*t[3]/t[2]:0);$('returnValue').textContent=fmt(t[3])+' returned';$('bonus').textContent=pct(t[5]?100*t[6]/t[5]:0);$('bonusQty').textContent=fmt(t[6])+' bonus qty';$('topZone').textContent=top?top.name:'—';$('topZoneShare').textContent=pct(top&&t[1]?100*top.s26/t[1]:0)+' share';$('growCount').textContent=c.gc;$('declineCount').textContent=c.dc;compare(z);donut(z,t[1]);trend(a);bars('zoneGrowth',z,'growth',{percent:true});bars('zoneExpiry',z,'exp26');bars('productSales',p,'s26');bars('productGrowth',p,'growth',{percent:true});bars('productExpiry',p,'exp26');bars('productBonus',p,'bonusRate',{percent:true});bars('zoneReturn',z,'returnRate',{percent:true});bars('zoneBonus',z,'bonusRate',{percent:true});$('zoneBody').innerHTML=z.sort((a,b)=>b.s26-a.s26).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc([...x.states].join(', '))}</td><td>${fmt(x.s26)}</td><td>${fmt(x.s25)}</td><td class="${(x.growth||0)>=0?'pos':'neg'}">${x.growth==null?'—':pct(x.growth)}</td><td>${pct(t[1]?100*x.s26/t[1]:0)}</td><td>${fmt(x.exp26)}</td><td>${pct(x.expiryRate)}</td><td>${pct(x.returnRate)}</td><td>${pct(x.bonusRate)}</td></tr>`).join('');$('productBody').innerHTML=p.sort((a,b)=>b.s26-a.s26).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc([...x.lines].join(', '))}</td><td>${fmt(x.s26)}</td><td>${fmt(x.s25)}</td><td class="${(x.growth||0)>=0?'pos':'neg'}">${x.growth==null?'—':pct(x.growth)}</td><td>${fmt(x.exp26)}</td><td>${pct(x.expiryRate)}</td><td>${pct(x.returnRate)}</td><td>${pct(x.bonusRate)}</td></tr>`).join('');ctable('growthBody',c.g);ctable('declineBody',c.d);bars('growBars',c.g.map(x=>({name:x.name,delta:x.delta})),'delta',{n:10});bars('declineBars',c.d.map(x=>({name:x.name,delta:x.delta})),'delta',{n:10,asc:true});const scope=sel.month.size?[...sel.month].map(x=>x.slice(0,3)).join(', '):'Jan–Aug';$('insights').innerHTML=`<div class="insight"><span>Selected Period</span><strong>${esc(scope)}</strong><small>Same months compared in 2025 and 2026</small></div><div class="insight"><span>Data Source</span><strong>New Excel sheets</strong><small>${D.i.length} Items • ${D.l.length} Lines • ${D.s.length} States • ${D.z.length} Zones</small></div>`}
$('search').addEventListener('input',render);$('reset').onclick=()=>{Object.values(sel).forEach(s=>s.clear());$('search').value='';refresh();render()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')});render();