const D=window.BARADE_SUMMARY,$=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(n)||0),pct=n=>(Number.isFinite(Number(n))?Number(n):0).toFixed(1)+'%',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COLORS=['#31ecff','#a855f7','#ff4fd8','#35efad','#ffcc65','#5f8cff','#00c3ff','#ff6b81'];
const sets={item:new Set(),line:new Set(),state:new Set(),zone:new Set()},defs={item:{vals:D.i,label:'All Items'},line:{vals:D.l,label:'All Lines'},state:{vals:D.s,label:'All States'},zone:{vals:D.z,label:'All Zones'}};
function multi(id,cfg){const sel=$(id);sel.style.display='none';const w=document.createElement('div');w.className='multi';sel.parentNode.appendChild(w);w.innerHTML=`<button class="multiBtn" type="button"><span>${cfg.label}</span><b>⌄</b></button><div class="multiMenu"><div class="multiActions"><button data-a="all">Select All</button><button data-a="clear">Clear</button></div><div class="multiList">${cfg.vals.map(v=>`<label><input type="checkbox" value="${esc(v)}"><span>${esc(v)}</span></label>`).join('')}</div></div>`;const btn=w.querySelector('.multiBtn'),menu=w.querySelector('.multiMenu');function sync(){w.querySelectorAll('input').forEach(x=>x.checked=sets[id].has(x.value));btn.querySelector('span').textContent=!sets[id].size?cfg.label:sets[id].size===1?[...sets[id]][0]:`${sets[id].size} selected`}btn.onclick=e=>{e.stopPropagation();document.querySelectorAll('.multi.open').forEach(x=>x!==w&&x.classList.remove('open'));w.classList.toggle('open')};menu.onclick=e=>e.stopPropagation();w.querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?sets[id].add(x.value):sets[id].delete(x.value);sync();render()});w.querySelector('[data-a=all]').onclick=()=>{cfg.vals.forEach(v=>sets[id].add(v));sync();render()};w.querySelector('[data-a=clear]').onclick=()=>{sets[id].clear();sync();render()};w._sync=sync}
Object.entries(defs).forEach(([k,v])=>multi(k,v));document.addEventListener('click',()=>document.querySelectorAll('.multi.open').forEach(x=>x.classList.remove('open')));
const fields={item:['item',D.i],line:['line',D.l],state:['state',D.s],zone:['zone',D.z]};
function rowsFor(dim){const [key,names]=fields[dim],rows=D.st[key];return rows.filter(r=>!sets[dim].size||sets[dim].has(names[r[0]])).map(r=>({name:names[r[0]],s25:r[1],o25:r[2],r25:r[3],e25:r[4],q25:r[5],b25:r[6],s26:r[7],o26:r[8],r26:r[9],e26:r[10],q26:r[11],b26:r[12]}));}
function activeDims(){return Object.keys(sets).filter(k=>sets[k].size)}
function scopeDim(){const a=activeDims();return a.length?a[a.length-1]:'item'}
function aggregate(rows){return rows.reduce((t,r)=>{for(const k of ['s25','o25','r25','e25','q25','b25','s26','o26','r26','e26','q26','b26'])t[k]=(t[k]||0)+(Number(r[k])||0);return t},{})}
function enrich(r){return {...r,growth:r.s25>0?100*(r.s26-r.s25)/r.s25:null,expiry:r.e26,expiryRate:r.o26?100*r.e26/r.o26:0,returnRate:r.o26?100*r.r26/r.o26:0,bonusRate:r.q26?100*r.b26/r.q26:0}}
function bars(id,a,key,opt={}){const el=$(id);a=[...a].filter(x=>x[key]!=null).sort((x,y)=>(opt.asc?1:-1)*((x[key]||0)-(y[key]||0))).slice(0,opt.n||14);const mx=Math.max(1,...a.map(x=>Math.abs(x[key]||0)));el.innerHTML=a.length?a.map(x=>`<div class="bar"><div class="name" title="${esc(x.name)}">${esc(x.name)}</div><div class="track"><div class="fill" style="width:${Math.abs(x[key]||0)/mx*100}%;${opt.color?`background:${opt.color}`:''}"></div></div><div class="value">${opt.percent?pct(x[key]):fmt(x[key])}</div></div>`).join(''):'<div class="note">No matching data</div>'}
function compare(a){a=[...a].sort((x,y)=>y.s26-x.s26).slice(0,15);const mx=Math.max(1,...a.flatMap(x=>[x.s25,x.s26]));$('zoneCompare').innerHTML=a.map(x=>`<div class="bar"><div class="name">${esc(x.name)}</div><div><div class="track"><div class="fill" style="width:${Math.max(0,x.s26)/mx*100}%;background:#31ecff"></div></div><div class="track" style="margin-top:3px"><div class="fill" style="width:${Math.max(0,x.s25)/mx*100}%;background:#a855f7"></div></div></div><div class="value">${fmt(x.s26)}</div></div>`).join('')}
function donut(a,total){a=[...a].filter(x=>x.s26>0).sort((x,y)=>y.s26-x.s26);let p=a.slice(0,7),known=p.reduce((s,x)=>s+x.s26,0);if(total-known>1)p.push({name:'Others',s26:total-known});let acc=0,st=[];p.forEach((x,i)=>{const v=total?x.s26/total*100:0;st.push(`${COLORS[i%COLORS.length]} ${acc}% ${acc+v}%`);acc+=v});$('donut').style.background=p.length?`conic-gradient(${st.join(',')})`:'rgba(255,255,255,.05)';$('donutTotal').textContent=fmt(total);$('donutLegend').innerHTML=p.map((x,i)=>`<div class="legendItem"><span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${COLORS[i%COLORS.length]};margin-inline-end:6px"></i>${esc(x.name)}</span><strong>${pct(total?100*x.s26/total:0)}</strong></div>`).join('')}
function trend(){const el=$('trend'),v=D.mt,mx=Math.max(1,...v[0],...v[1]),xy=(n,i)=>[55+i*112,270-n/mx*220],path=a=>a.map((n,i)=>(i?'L':'M')+xy(n,i).join(',')).join(' '),months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug'];el.innerHTML=`<path d="${path(v[0])}" fill="none" stroke="#a855f7" stroke-width="4"/><path d="${path(v[1])}" fill="none" stroke="#31ecff" stroke-width="4"/>`+months.map((m,i)=>`<text x="${55+i*112}" y="300" class="axis" text-anchor="middle">${m}</text>`).join('')}
function customers(){const q=($('search').value||'').toLowerCase(),filter=a=>a.filter(r=>(!sets.state.size||sets.state.has(D.s[r[2]]))&&(!sets.zone.size||sets.zone.has(D.z[r[3]]))&&(!q||D.n[r[1]].toLowerCase().includes(q)||D.n[r[0]].toLowerCase().includes(q))).map(r=>({acct:D.n[r[0]],name:D.n[r[1]],state:D.s[r[2]],zone:D.z[r[3]],s25:r[4],s26:r[5],growth:r[6],delta:r[7]}));return {g:filter(D.cg),d:filter(D.cd)}}
function ctable(id,a){$(id).innerHTML=a.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.acct)}</td><td>${esc(x.state)}</td><td>${esc(x.zone)}</td><td>${fmt(x.s25)}</td><td>${fmt(x.s26)}</td><td class="${x.growth>=0?'pos':'neg'}">${pct(x.growth)}</td><td class="${x.delta>=0?'pos':'neg'}">${x.delta>=0?'+':''}${fmt(x.delta)}</td></tr>`).join('')||'<tr><td colspan="9">No matching customers</td></tr>'}
function render(){const dim=scopeDim(),base=rowsFor(dim).map(enrich),t=aggregate(base),zoneRows=rowsFor('zone').map(enrich),itemRows=rowsFor('item').map(enrich),growth=t.s25?100*(t.s26-t.s25)/t.s25:null,top=[...zoneRows].sort((a,b)=>b.s26-a.s26)[0],c=customers(),multiDim=activeDims().length>1;$('sales26').textContent=fmt(t.s26);$('sales25').textContent='2025: '+fmt(t.s25);$('growth').textContent=growth==null?'—':pct(growth);$('growth').className=growth>=0?'pos':'neg';$('expiry').textContent=fmt(t.e26);$('expiryRate').textContent=pct(t.o26?100*t.e26/t.o26:0)+' of Sold Amount';$('returnRate').textContent=pct(t.o26?100*t.r26/t.o26:0);$('returnValue').textContent=fmt(t.r26)+' returned';$('bonus').textContent=pct(t.q26?100*t.b26/t.q26:0);$('bonusQty').textContent=fmt(t.b26)+' bonus qty';$('topZone').textContent=top?top.name:'—';$('topZoneShare').textContent=pct(top&&t.s26?100*top.s26/t.s26:0)+' share';$('growCount').textContent=c.g.length;$('declineCount').textContent=c.d.length;compare(zoneRows);donut(zoneRows,t.s26);trend();bars('zoneGrowth',zoneRows,'growth',{percent:true});bars('zoneExpiry',zoneRows,'expiry');bars('productSales',itemRows,'s26');bars('productGrowth',itemRows,'growth',{percent:true});bars('productExpiry',itemRows,'expiry');bars('productBonus',itemRows,'bonusRate',{percent:true});bars('zoneReturn',zoneRows,'returnRate',{percent:true});bars('zoneBonus',zoneRows,'bonusRate',{percent:true});$('zoneBody').innerHTML=zoneRows.sort((a,b)=>b.s26-a.s26).map(x=>`<tr><td>${esc(x.name)}</td><td>—</td><td>${fmt(x.s26)}</td><td>${fmt(x.s25)}</td><td>${x.growth==null?'—':pct(x.growth)}</td><td>${pct(t.s26?100*x.s26/t.s26:0)}</td><td>${fmt(x.expiry)}</td><td>${pct(x.expiryRate)}</td><td>${pct(x.returnRate)}</td><td>${pct(x.bonusRate)}</td></tr>`).join('');$('productBody').innerHTML=itemRows.sort((a,b)=>b.s26-a.s26).map(x=>`<tr><td>${esc(x.name)}</td><td>—</td><td>${fmt(x.s26)}</td><td>${fmt(x.s25)}</td><td>${x.growth==null?'—':pct(x.growth)}</td><td>${fmt(x.expiry)}</td><td>${pct(x.expiryRate)}</td><td>${pct(x.returnRate)}</td><td>${pct(x.bonusRate)}</td></tr>`).join('');ctable('growthBody',c.g);ctable('declineBody',c.d);bars('growBars',c.g.map(x=>({name:x.name,delta:x.delta})),'delta');bars('declineBars',c.d.map(x=>({name:x.name,delta:x.delta})),'delta',{asc:true});$('insights').innerHTML=`<div class="insight"><span>Data Status</span><strong>Loaded</strong><small>${D.i.length} Items • ${D.z.length} Zones</small></div><div class="insight"><span>Selected Scope</span><strong>${activeDims().length?activeDims().join(' + '):'All Data'}</strong><small>${multiDim?'Summary fallback: combined dimensions shown by latest selected dimension':'Exact aggregate for selected dimension'}</small></div>`}
$('search').addEventListener('input',render);$('reset').onclick=()=>{Object.values(sets).forEach(s=>s.clear());document.querySelectorAll('.multi').forEach(x=>x._sync&&x._sync());$('search').value='';render()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')});render();